Sure, here's the contents for the file: /LotrySol/LotrySol/programs/lottery/Xargo.toml

[package]
name = "lottery"
version = "0.1.0"
authors = ["Your Name <you@example.com>"]
edition = "2018"

[dependencies]
anchor-lang = "0.17.0"
solana-program = "1.9.0"

[profile.dev]
opt-level = "2"

[profile.release]
opt-level = "3"